#!/usr/bin/env python3
"""Emit the end-to-end eval configs for the input-ALLOCATION study.

The doc's "Which input coordinates, and how many per expert?" section ranks four ways
of splitting a token's pooled coordinate-read budget across its K experts, all at an
identical pooled budget of `K*round(rho_input*H)` reads/token:

    uniform   |x_i|              same coordinate set for all K experts
    router    g_e*|x_i|          pooled top-N across (slot, coord)      <- best practice
    router2   g_e^2*|x_i|        sharper; offline said it overshoots
    colnorm   |x_i|*rms_j(W)     equal per-expert budget, reweighted |x|

That ranking was established **offline only** (block-output rel_err, 4 layers x 4096
C4 tokens). `uniform` and `router` were later confirmed end-to-end, but `router2` and
`colnorm` never were -- and the `input_only` sweep has since shown the offline
instrument can mis-rank outright. This generator fills the gap.

What already exists end-to-end at rho_input=0.25 (do NOT re-run):

    rho_ch  uniform            router
    0.10    74.06 / 77.20      74.64 / 77.67   (leaderboard rows 6, 7)
    0.15    76.47 / 78.63      -- MISSING, generated here
    0.20    76.72 / 79.10      76.61 / 79.45   (reuse_k25_r20 vs bp_cut633; iso, B=1229)

So this emits six configs:

    router  @ rho_ch=0.15   x {hellaswag, mmlu}   -- fills the middle of the trend; RUN
    router2 @ rho_ch=0.10   x {hellaswag, mmlu}   -- NOT RUN (see below)
    colnorm @ rho_ch=0.10   x {hellaswag, mmlu}   -- NOT RUN (see below)

The router2/colnorm evals were started and then cancelled: both are predicted to land
*below* `router`, neither is a best-practice candidate, and the ladder is well calibrated
at this budget (`router`'s residual is -0.08pt HS / -0.04pt MMLU), so ~26 GPU-hours to
confirm a term nobody would ship was not worth it. The configs are kept ready in case
the question is revisited -- `router2` is the one worth the time, since sharper `g_e`
weighting is what Level-1 found BETTER for the channel budget. Opt in via
`ARMS="router2_k25_r10 colnorm_k25_r10" bash scripts/run_probe_alloc_study.sh ...`.

Every other knob is held at exactly the rows-6/7 setting (bits=16, group=128,
use_gate=true, lam=1.0, k_min=0, rho_input=0.25) so the only thing that varies is
`input_alloc` and, for the trend rows, `rho_channel`.
"""
import os

# (input_alloc, rho_channel, filename tag, why, status)
POINTS = [
    ("router2", 0.10, "router2_k25_r10",
     "sharper g^2 weighting; offline rel_err 0.4272 vs router's 0.4183 -> predicted "
     "+0.01..+0.43pt over uniform, i.e. it gives back most of router's gain",
     "NOT RUN -- predicted below `router`, not a best-practice candidate. Ready if the\n#   question is revisited; this is the one of the two worth the GPU time, since\n#   sharper g_e weighting is what Level-1 found BETTER for the CHANNEL budget."),
    ("colnorm", 0.10, "colnorm_k25_r10",
     "reweight |x_i| by rms_j(W[:,i]); offline rel_err 0.4429 vs uniform's 0.4434 -> "
     "predicted a wash (+0.01pt), column-norm CV is only 0.022",
     "NOT RUN -- predicted a wash against `uniform`; nothing to ship either way."),
    ("router",  0.15, "rtr_k25_r15",
     "fills the middle of the uniform-vs-router trend; uniform at this budget is "
     "measured at 76.47 / 78.63 (leaderboard row 5)",
     "RUN -- this is the arm that answers whether router's +0.58pt at rho_ch=0.10\n#   decays smoothly to the -0.11pt measured at rho_ch=0.20."),
]
K, I, H = 8, 768, 2048
SCORES = "/home/ubuntu/yequan/moe-compression/results/Qwen_Qwen3-30B-A3B-Thinking-2507/c4/scores"

TMPL = """# input_sparse input-ALLOCATION study: input_alloc={alloc} at rho_channel={rho_ch:g}.
#
# Auto-generated by scripts/gen_probe_alloc_configs.py -- edit that, not this.
#
# WHY THIS CONFIG EXISTS. The doc's "Which input coordinates, and how many per expert?"
# section ranks four allocation terms from an OFFLINE rel_err screen only. `uniform` and
# `router` were later confirmed end-to-end (+0.58pt HS / +0.47pt MMLU at rho_ch=0.10,
# leaderboard rows 6 -> 7), but this arm never was:
#
#   {why}
#
# STATUS: {status}
#
# All four terms spend the IDENTICAL pooled budget of K*round(rho_input*H)
# = {K}*{reads} = {pooled} coordinate reads per token; they differ only in how it is
# split across the token's K experts. Every other knob is held at the rows-6/7 value,
# so `input_alloc`{extra} is the only thing that moves.
#
#   used = rho_channel + 2*rho_input/3 = {rho_ch:.5f} + {scoring:.5f} = {used:.5f}
#          -> {cut} used-parameter cut
#   B = {B} of K*I={KI} channels/token,  {reads} coordinate reads/expert-equivalent
#
# Verify the in-run log prints USED PARAMS={used:.4f}, input_alloc={alloc}, B={B},
# and extra proxy storage = 0.0%.
#
# Masking simulation, no fine-tuning.
test_only: true

model_name_or_path: "Qwen/Qwen3-30B-A3B-Thinking-2507"
load_in_4bit: false
load_in_8bit: false
trust_remote_code: true

test_speed: false
real_slim: false
shrink_gate: false

device: "cuda"
dtype: "bf16"
use_wandb: true
wandb_project: "yequan26-a100-qwen3-30b-eval"
wandb_name: "{name}"

num_workers: 0

eval_sample_limit: -1
eval_split: "test"
per_device_eval_batch_size: {bs_dev}
batch_size: {bs}
num_fewshot: {shots}

prune_kwargs:
  prune_ratio: {prune:.5f}        # = 1 - rho_channel
  dynamic_alloc:
    enabled: true
    criterion: "sparse_probe"
    k_min: 0
    probe:
      bits: 16                  # probe aliases the served weights -> zero extra storage
      group: 128
      rho_input: 0.25           # held at the rows-6/7 value
      rho_channel: {rho_ch:.5f}
      use_gate: true
      lam: 1.0
      input_alloc: "{alloc}"

eval_task_names: "{task}"
output_dir: ./results_eval/{name}
scores_dir: {scores}

attn_implementation: "sdpa"
"""

TASKS = {"hellaswag": dict(task="hellaswag", shots=0, bs_dev=4, bs=16),
         "mmlu": dict(task="mmlu", shots=5, bs_dev=8, bs=8)}
RHO_IN = 0.25


def main():
    out_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                           "configs", "eval")
    rows = []
    for alloc, rho_ch, tag, why, status in POINTS:
        used = rho_ch + 2 * RHO_IN / 3.0
        B = int(round(rho_ch * K * I))
        reads = int(round(RHO_IN * H))
        for tname, tk in TASKS.items():
            name = f"qwen3_30b_a3b_probe_alloc_{tag}_{tname}"
            body = TMPL.format(
                alloc=alloc, rho_ch=rho_ch, why=why, status=status, used=used,
                scoring=2 * RHO_IN / 3.0, cut=f"-{100 * (1 - used):.1f}%",
                B=B, KI=K * I, K=K, reads=reads, pooled=K * reads,
                prune=1.0 - rho_ch, name=name, scores=SCORES,
                extra="" if rho_ch == 0.10 else " (and rho_channel)",
                **tk)
            with open(os.path.join(out_dir, f"{name}.yaml"), "w") as f:
                f.write(body)
            rows.append((name, alloc, rho_ch, used, B, reads, status.split()[0]))
    print(f"wrote {len(rows)} configs to {out_dir}\n")
    print(f"{'config':56s} {'alloc':8s} {'rho_ch':>7s} {'used':>7s} {'cut':>7s} {'B':>5s}  run?")
    for name, alloc, rho_ch, used, B, reads, st in rows:
        print(f"{name:56s} {alloc:8s} {rho_ch:7.3f} {used:7.4f} {100*(1-used):6.1f}% {B:5d}  {st}")


if __name__ == "__main__":
    main()
