#!/usr/bin/env python3
"""Emit the `input_sparse` best-practice eval configs for the used-param sweep curve.

One config per (budget, task). Every knob follows "Current best practice for
input_sparse" in docs/exps/dynamic_active_param/efficient_scorer.md:
``bits=16`` (probe aliases the served weight, zero extra storage), ``use_gate=true``
(both branches), ``input_alloc=router``, ``lam=1.0``, ``k_min=0``, no per-layer
schedule. Only the two sparsities move, and they come from the solved iso-cost
split (``scripts/probe_split_solve.py``), NOT from hand-picking rho_input.

The existing reuse_k25_r* configs are NOT reusable for this curve: they set
``input_alloc: uniform``, so they are off best-practice by the measured +0.58pt.
"""
import os

# (target cut %, rho_input, rho_channel) -- verbatim from the doc's
# "Choosing the two sparsities at a new budget" table.
POINTS = [
    (63.3, 0.2500, 0.20003),
    (68.3, 0.2400, 0.15670),
    (73.3, 0.1875, 0.14170),
    (75.0, 0.1875, 0.12500),   # already measured on HellaSwag (74.08)
    (77.5, 0.1875, 0.10000),
    (80.0, 0.1575, 0.09500),
]
K, I, H = 8, 768, 2048
SCORES = "/home/ubuntu/yequan/moe-compression/results/Qwen_Qwen3-30B-A3B-Thinking-2507/c4/scores"

TMPL = """# input_sparse BEST PRACTICE, curve point at {cut} used-parameter cut.
#
# Auto-generated by scripts/gen_probe_curve_configs.py -- edit that, not this.
# Settings follow "Current best practice for input_sparse" in
# docs/exps/dynamic_active_param/efficient_scorer.md: bits=16 (the probe aliases the
# served up/gate weights -> ZERO extra storage), use_gate=true (score BOTH branches),
# input_alloc=router (+0.58pt HS / +0.47pt MMLU at identical cost), lam=1.0, k_min=0,
# and one global (rho_input, rho_channel) for all 48 layers (per-layer schedules are
# a closed negative result).
#
# The two sparsities are SOLVED at this budget, not hand-picked
# (scripts/probe_split_solve.py):
#   used = rho_channel + 2*rho_input/3 = {used:.5f}  ->  {cut} cut
#   scoring 2*rho_input/3 = {scoring:.5f} ({score_share:.1f}% of budget)
#   compute rho_channel   = {rho_ch:.5f} ({comp_share:.1f}% of budget)
#   B = {B} of K*I={KI} channels/token,  {reads} coordinate reads/expert
# Verify the in-run log prints USED PARAMS={used:.4f} and extra proxy storage = 0.0%.
#
# Masking simulation, no fine-tuning.
test_only: true

model_name_or_path: "Qwen/Qwen3-30B-A3B-Thinking-2507"
load_in_4bit: false
load_in_8bit: false
trust_remote_code: true

test_speed: false
real_slim: false
shrink_gate: false

device: "cuda"
dtype: "bf16"
use_wandb: true
wandb_project: "yequan26-a100-qwen3-30b-eval"
wandb_name: "{name}"

num_workers: 0

eval_sample_limit: -1
eval_split: "test"
per_device_eval_batch_size: {pdbs}
batch_size: {bs}
num_fewshot: {fs}

prune_kwargs:
  prune_ratio: {prune_ratio:.5f}        # = 1 - rho_channel
  dynamic_alloc:
    enabled: true
    criterion: "sparse_probe"
    k_min: 0
    probe:
      bits: 16
      group: 128
      rho_input: {rho_in}
      rho_channel: {rho_ch:.5f}
      use_gate: true
      lam: 1.0
      input_alloc: "router"

eval_task_names: "{task}"
output_dir: ./results_eval/{name}
scores_dir: {scores}

attn_implementation: "sdpa"
"""


def main():
    repo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = os.path.join(repo, "configs/eval")
    made = []
    for cut, p, r in POINTS:
        used = r + 2 * p / 3
        # the label is the rounded cut; assert it matches the exact budget to 0.05pp
        assert abs(100 * (1 - used) - cut) < 0.05, f"{cut}: used={used}"
        tag = f"{cut:.1f}".replace(".", "")          # 63.3 -> 633
        for task, fs, pdbs, bs in (("hellaswag", 0, 4, 16), ("mmlu", 5, 8, 8)):
            name = f"qwen3_30b_a3b_probe_bp_cut{tag}_{task}"
            body = TMPL.format(
                cut=f"-{cut:.1f}%", used=used, scoring=2 * p / 3, rho_ch=r,
                score_share=100 * (2 * p / 3) / used,
                comp_share=100 * r / used,
                B=round(r * K * I), KI=K * I, reads=round(p * H),
                name=name, rho_in=p, prune_ratio=1 - r,
                task=task, fs=fs, pdbs=pdbs, bs=bs, scores=SCORES,
            )
            path = os.path.join(out, f"{name}.yaml")
            with open(path, "w") as f:
                f.write(body)
            made.append((name, cut, p, r, used, round(r * K * I), round(p * H)))
    print(f"{'config':52s} {'cut':>7} {'rho_in':>7} {'rho_ch':>8} {'used':>7} {'B':>5} {'reads':>6}")
    for n, cut, p, r, u, B, rd in made:
        print(f"{n:52s} {-cut:6.1f}% {p:7.4f} {r:8.5f} {u:7.5f} {B:5d} {rd:6d}")
    print(f"\n{len(made)} configs written to {out}")


if __name__ == "__main__":
    main()
