#!/usr/bin/env python3
"""Emit the `input_only` eval configs — one-pass input sparsity at three budgets.

`input_only` uses input sparsity for the **computation**, not for a scorer: gate/up
read only the token's top-``rho_input`` coordinates by ``|x|`` and that sparse
intermediate IS the FFN's intermediate; ``down`` is then gathered to the pooled
top-B channels. Cost is a plain read count::

    used = (2*rho_input + rho_channel) / 3

Two arms per budget, the question the sweep answers:

* ``uniform`` — every one of the token's K experts reads the same coordinate set.
* ``router``  — the pooled coordinate-read budget is split across the token's K
  experts by ``g_e*|x_i|`` (``allocate_input_reads``, beta=1). Offline this is worth
  **+2.4 to +3.6pt** here versus +0.75 to +1.1pt for the two-pass scorer, because a
  sparse read now corrupts the expert's *values* and not just its ranking.

**Split.** Both knobs are set to the budget itself (``rho_input = rho_channel = C``),
which is the symmetric point — read the same fraction of every matrix's own input —
and lands the used-parameter cut exactly on the target. The offline screen
(``scripts/input_only_error.py``, 4 layers x 8192 C4 tokens) puts the true optimum a
hair toward more scoring (0.35/0.20, 0.275/0.20, 0.225/0.15 at the three budgets)
but only by **0.07 / 0.17 / 0.29 pt-equivalent**, i.e. inside the instrument's noise
and inside the range where this repo has already measured iso-cost split changes to
be a wash. Symmetric it is.
"""
import os

# target used-parameter cut (%) -> the symmetric sparsity, which equals `used`
CUTS = [70.0, 75.0, 80.0]
ARMS = [("uni", "uniform"), ("rtr", "router")]
K, I, H = 8, 768, 2048
SCORES = "/home/ubuntu/yequan/moe-compression/results/Qwen_Qwen3-30B-A3B-Thinking-2507/c4/scores"

TMPL = """# input_only (ONE-PASS input sparsity) at a {cut} used-parameter cut, {alloc} allocation.
#
# Auto-generated by scripts/gen_input_only_configs.py -- edit that, not this.
#
# THE METHOD. Per token, gate_proj and up_proj read only the top rho_input={rho:.5f}
# fraction of the token's input coordinates by |x|, and that sparse-input SwiGLU
# intermediate IS what feeds down_proj -- there is no proxy and no exact re-read, so
# the reads that decide are the reads that compute. down_proj is then gathered to the
# pooled top-B channels by g_e*|h~|, i.e. oracle_mag_noW's rule applied to the values
# actually being computed (the selection therefore costs nothing).
#
# Read uniformly: every matrix of the expert FFN reads only the largest-magnitude
# coordinates of ITS OWN input -- x for gate/up, the intermediate for down. One
# sparsity, applied three times, which is why rho_input = rho_channel = {rho:.5f}
# lands the cut exactly on {cut}.
#
#   used = (2*rho_input + rho_channel)/3 = ({two_p:.5f} + {rho:.5f})/3 = {used:.5f}  ->  {cut} cut
#     gate+up reads  2*rho_input/3 = {gu:.5f}  ({gu_share:.1f}% of budget)
#     down reads       rho_channel/3 = {dn:.5f}  ({dn_share:.1f}% of budget)
#   B = {B} of K*I={KI} channels/token,  {reads} coordinate reads/expert
#
# NOTE the cost asymmetry is INVERTED versus two-pass input_sparse: here a unit of
# rho_channel costs 1/3 and a unit of rho_input costs 2/3, so rho_channel is the CHEAP
# axis. "Cut rho_input first" does not carry over from that method.
#
# input_alloc={alloc}: {alloc_note}
#
# Verify the in-run log prints USED PARAMS={used:.4f} and B={B}.
# Masking simulation for down_proj only (arithmetic identical to a real gather); the
# gate/up input sparsity is NOT simulated -- it genuinely changes the numbers.
test_only: true

model_name_or_path: "Qwen/Qwen3-30B-A3B-Thinking-2507"
load_in_4bit: false
load_in_8bit: false
trust_remote_code: true

test_speed: false
real_slim: false
shrink_gate: false

device: "cuda"
dtype: "bf16"
use_wandb: true
wandb_project: "yequan26-a100-qwen3-30b-eval"
wandb_name: "{name}"

num_workers: 0

eval_sample_limit: -1
eval_split: "test"
per_device_eval_batch_size: {bs_dev}
batch_size: {bs}
num_fewshot: {shots}

prune_kwargs:
  prune_ratio: {prune:.5f}        # = 1 - rho_channel
  dynamic_alloc:
    enabled: true
    criterion: "input_only"
    k_min: 0
    input_only:
      rho_input: {rho:.5f}        # coordinates gate/up read (and compute on)
      rho_channel: {rho:.5f}      # channels down_proj reads
      input_alloc: "{alloc}"

eval_task_names: "{task}"
output_dir: ./results_eval/{name}
scores_dir: {scores}

attn_implementation: "sdpa"
"""

ALLOC_NOTE = {
    "uniform": ("all K of the token's experts read the SAME coordinate set, so the "
                "coordinate\n#   choice is a property of the token alone."),
    "router": ("the pooled read budget K*round(rho_input*H) is split across the "
               "token's K\n#   experts by g_e*|x_i| (one bisection on a threshold over "
               "the shared |x| order),\n#   so a dominated expert reads fewer "
               "coordinates. Identical cost and reads/token."),
}
TASKS = {"hellaswag": dict(task="hellaswag", shots=0, bs_dev=4, bs=16),
         "mmlu": dict(task="mmlu", shots=5, bs_dev=8, bs=8)}


def main():
    out_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                           "configs", "eval")
    written = []
    for cut in CUTS:
        used = rho = round(1.0 - cut / 100.0, 5)
        B = int(round(rho * K * I))
        reads = int(round(rho * H))
        for tag, alloc in ARMS:
            for tname, tk in TASKS.items():
                name = f"qwen3_30b_a3b_inputonly_{tag}_cut{int(round(cut * 10))}_{tname}"
                body = TMPL.format(
                    cut=f"-{cut:.1f}%", rho=rho, used=used, two_p=2 * rho,
                    gu=2 * rho / 3.0, dn=rho / 3.0,
                    gu_share=100 * (2 * rho / 3.0) / used,
                    dn_share=100 * (rho / 3.0) / used,
                    B=B, KI=K * I, reads=reads, prune=1.0 - rho,
                    alloc=alloc, alloc_note=ALLOC_NOTE[alloc],
                    name=name, scores=SCORES, **tk)
                p = os.path.join(out_dir, f"{name}.yaml")
                with open(p, "w") as f:
                    f.write(body)
                written.append((name, used, rho, B, reads, alloc, tname))
    print(f"wrote {len(written)} configs to {out_dir}\n")
    print(f"{'config':58s} {'used':>7s} {'cut':>7s} {'rho':>7s} {'B':>5s} {'reads':>6s}")
    for name, used, rho, B, reads, alloc, tname in written:
        print(f"{name:58s} {used:7.4f} {100*(1-used):6.1f}% {rho:7.4f} {B:5d} {reads:6d}")


if __name__ == "__main__":
    main()
