#!/usr/bin/env bash
# BEST-PRACTICE used-parameter sweep for input_sparse -- the curve points.
#
# One eval per (budget, task) at the SOLVED iso-cost (rho_input, rho_channel) for
# that budget, all other knobs at best practice (bits=16, use_gate=true,
# input_alloc=router, lam=1.0, k_min=0, no per-layer schedule). Configs are
# generated by scripts/gen_probe_curve_configs.py.
#
#   cut      rho_in  rho_ch    B    reads
#   -63.3%   0.2500  0.20003  1229   512
#   -68.3%   0.2400  0.15670   963   492
#   -73.3%   0.1875  0.14170   871   384
#   -75.0%   0.1875  0.12500   768   384   <- ALREADY MEASURED (probe_router_split_opt)
#   -77.5%   0.1875  0.10000   614   384
#   -80.0%   0.1575  0.09500   584   323
#
# The existing reuse_k25_r{10,15,20} rows are NOT on this curve: they used
# input_alloc=uniform, which is off best practice by the measured +0.58pt.
#
# GPU RULES (learned the hard way):
#   * MMLU 5-shot needs 4 GPUs. On 2x40GB it OOMs -- one run died at 99% after
#     ~10h. Never economize on MMLU.
#   * HellaSwag 0-shot is fine on 2 GPUs (two such runs completed rc 0).
# So HS jobs are paired 2+2 on a 4-GPU block; MMLU jobs run one at a time on all 4.
#
# Usage:
#   GPUS=0,1,2,3 bash scripts/run_probe_curve_sweep.sh hs      # all HellaSwag
#   GPUS=0,1,2,3 bash scripts/run_probe_curve_sweep.sh mmlu    # all MMLU
#   GPUS=0,1,2,3 bash scripts/run_probe_curve_sweep.sh all     # HS then MMLU
# Capacity is usually fragmented across the boxes, so the work list is splittable:
#   CUTS="633 733 800" GPUS=6,7 bash scripts/run_probe_curve_sweep.sh hs
# HellaSwag accepts a 2-GPU block; MMLU always demands 4 and refuses fewer.
set -u
cd "$(dirname "$0")/.."
export PYTHONPATH="$(pwd):$(pwd)/src"
mkdir -p run_logs

GPUS="${GPUS:-0,1,2,3}"
MODE="${1:-all}"

# budgets still needing an eval (-75.0% HS is done; its MMLU runs elsewhere)
HS_CUTS="${CUTS:-633 683 733 775 800}"
MMLU_CUTS="${CUTS:-633 683 733 775 800}"

IFS=',' read -r -a G <<< "$GPUS"
NG="${#G[@]}"
# MMLU 5-shot OOMs on 2x40GB -- refuse rather than waste ~10h discovering it again.
if { [ "$MODE" = "mmlu" ] || [ "$MODE" = "all" ]; } && [ "$NG" -lt 4 ]; then
  echo "[curve] ERROR: MMLU needs 4 GPUs (2 OOMs at 99%); got $GPUS" >&2; exit 1
fi
if [ "$NG" -lt 2 ]; then
  echo "[curve] ERROR: need >=2 GPUs, got $GPUS" >&2; exit 1
fi
if [ "$NG" -ge 4 ]; then
  HALF_A="${G[0]},${G[1]}"
  HALF_B="${G[2]},${G[3]}"
else
  # 2-GPU block: run HellaSwag jobs one at a time on the whole block
  HALF_A="$GPUS"
  HALF_B=""
fi

run_one() {  # name cfg gpus
  local stamp; stamp=$(date +%m%d-%H%M%S)
  echo "[curve] start $1 on gpu $3 @ $stamp"
  CUDA_VISIBLE_DEVICES=$3 .venv/bin/python src/train/merge_slim_eval.py \
    --config "configs/eval/$2" > "run_logs/${1}_${stamp}.log" 2>&1
  echo "[curve] done  $1 (rc $?)"
}

# ---- HellaSwag: two at a time, 2 GPUs each -------------------------------- #
if [ "$MODE" = "hs" ] || [ "$MODE" = "all" ]; then
  set -- $HS_CUTS
  while [ "$#" -gt 0 ]; do
    a="$1"; shift
    if [ "$#" -gt 0 ] && [ -n "$HALF_B" ]; then
      b="$1"; shift
      run_one "bp_cut${a}_hs" "qwen3_30b_a3b_probe_bp_cut${a}_hellaswag.yaml" "$HALF_A" &
      pa=$!
      run_one "bp_cut${b}_hs" "qwen3_30b_a3b_probe_bp_cut${b}_hellaswag.yaml" "$HALF_B" &
      pb=$!
      wait $pa; wait $pb
    else
      run_one "bp_cut${a}_hs" "qwen3_30b_a3b_probe_bp_cut${a}_hellaswag.yaml" "$GPUS"
    fi
  done
  echo "[curve] HELLASWAG_DONE"
fi

# ---- MMLU: one at a time, all 4 GPUs ------------------------------------- #
if [ "$MODE" = "mmlu" ] || [ "$MODE" = "all" ]; then
  for c in $MMLU_CUTS; do
    run_one "bp_cut${c}_mmlu" "qwen3_30b_a3b_probe_bp_cut${c}_mmlu.yaml" "$GPUS"
  done
  echo "[curve] MMLU_DONE"
fi

echo "[curve] ALL_DONE"
